In [16]:
import pandas as pd
from sklearn.feature_selection import f_regression
from sklearn.preprocessing import StandardScaler

In [4]:
df = pd.read_csv (r'data.csv')
print (df)

             coe1       coe2       coe3       coe4       coe5       coe6  \
0     -710.556500   0.000000   0.000000   0.000000   0.000000   0.000000
1     -710.556500   0.000000   0.000000   0.000000   0.000000   0.000000
2     -547.729300  58.423172 -13.760821  33.484177  -7.508908  -0.751401
3     -431.293370  64.970245 -25.328407  37.369225 -14.686289   4.484373
4     -375.400330  66.278150 -25.174992  33.393127 -15.222846   7.396749
...           ...        ...        ...        ...        ...        ...
29744  -86.307014  46.474297 -27.960835  11.218966   3.086929 -12.722772
29745  -88.716020  46.612030 -30.019547   9.129774  -0.068393 -11.179683
29746  -89.869484  43.992280 -31.202278  10.022432  -3.468584 -12.126680
29747  -94.529030  44.139366 -31.213770   7.805181   0.542107  -8.369688
29748 -128.137270  40.980797 -28.018074   7.809144   0.048119  -6.397692

            coe7      coe8       coe9      coe10     coe11     coe12     coe13
0       0.000000  0.000000   0.000000   0.000000  0.000000  0.000000  0.000000
1       0.000000  0.000000   0.000000   0.000000  0.000000  0.000000  0.000000
2      -6.038508  3.357160  12.561382 -14.858431  6.623683  2.068609 -9.008942
3      -5.799687  7.137848  17.723553 -17.007643  8.995454 -1.925177 -2.404968
4      -8.221536  9.074163  17.919060 -19.958797  4.853339 -1.942278 -3.597352
...          ...       ...        ...        ...       ...       ...       ...
29744  11.716476 -6.265339   5.013133  -1.086962 -3.787698 -2.476840  2.515621
29745  10.462234 -9.248553   2.155163  -1.848183 -7.304120 -1.744738  6.825108
29746   9.627382 -7.348018   3.804848   1.685928 -5.363606 -4.236708  4.273725
29747  13.845150 -3.028122   5.785566  -2.548568 -1.917439 -1.614104  5.423120
29748  12.309546 -8.435227   2.390559  -4.324278 -0.871235  4.596220  7.502765

[29749 rows x 13 columns]

In [5]:
df.keys()

Index(['coe1', 'coe2', 'coe3', 'coe4', 'coe5', 'coe6', 'coe7', 'coe8', 'coe9',
       'coe10', 'coe11', 'coe12', 'coe13'],
      dtype='object')

In [7]:
df.shape

(29749, 13)

In [11]:
df.describe()

,coe1,coe2,coe3,coe4,coe5,coe6,coe7,coe8,coe9,coe10,coe11,coe12,coe13
count,29749.000000,29749.000000,29749.000000,29749.000000,29749.000000,29749.000000,29749.000000,29749.000000,29749.000000,29749.000000,29749.000000,29749.000000,29749.000000
mean,-305.679507,70.732094,-12.917524,38.857208,3.725492,7.030936,2.931293,5.452375,11.861431,-6.950837,6.331777,1.282213,1.921837
std,97.261328,39.694047,25.119604,15.106875,11.817523,11.451331,10.245038,7.516775,13.586746,10.942386,9.583295,6.446317,6.579926
min,-764.010130,-88.718640,-102.590060,-37.425274,-43.122140,-43.715286,-37.790020,-27.534689,-29.487701,-41.069412,-23.322430,-21.815376,-28.299866
25%,-361.264800,57.342697,-31.886183,29.853954,-4.019946,-0.480276,-4.360976,0.086391,0.878257,-15.614775,-0.903426,-2.675659,-2.181400
50%,-283.527950,75.399350,-18.870613,40.987934,3.229385,6.895924,1.155269,5.434874,13.257148,-6.883941,6.955846,1.700435,2.263755
75%,-243.707600,91.585260,3.704183,48.953564,11.227454,14.898180,8.324070,10.754604,23.301373,1.775230,13.892990,5.566758,6.396651
max,0.000000,239.735410,131.645920,90.046150,64.902115,59.624060,39.920853,38.312477,45.040100,29.071596,36.832550,27.569427,27.705265

Scaling coe into standard values

In [17]:
X = df

scaler = StandardScaler()
X_scaled = scaler.fit_transform(X)
X_scaled

array([[-4.16284463, -1.78196198,  0.51424941, ..., -0.66072093,
        -0.19890961, -0.29208077],
       [-4.16284463, -1.78196198,  0.51424941, ..., -0.66072093,
        -0.19890961, -0.29208077],
       [-2.48869582, -0.31010012, -0.03357183, ...,  0.03046034,
         0.12199358, -1.66125938],
       ...,
       [ 2.21890502, -0.67365928, -0.72791997, ..., -1.22041318,
        -0.85614993,  0.35743977],
       [ 2.17099673, -0.66995373, -0.72837747, ..., -0.86080573,
        -0.44930552,  0.5321247 ],
       [ 1.82544516, -0.74952793, -0.60115612, ..., -0.75163429,
         0.51410179,  0.84818908]])

In [10]:
from sklearn.decomposition import PCA

In [46]:
pca = PCA(0.95)
X_pca = pca.fit_transform(X_scaled)
X_pca.shape

(29749, 11)

In [47]:
X_pca

array([[ 2.90126875, -0.76108784, -2.91922873, ...,  1.0772468 ,
         0.08035126, -0.82842514],
       [ 2.90126875, -0.76108784, -2.91922873, ...,  1.0772468 ,
         0.08035126, -0.82842514],
       [ 0.70061074,  0.0265384 , -2.17520937, ...,  2.00561058,
         0.29990671, -0.52857813],
       ...,
       [ 0.73808159,  0.26212049, -1.51121745, ..., -2.1764957 ,
        -1.15912659,  0.27646654],
       [ 0.44478135,  0.27139934, -0.97130858, ..., -2.05661053,
        -1.44234291,  0.15463282],
       [ 0.60621864,  0.6153529 , -1.32898433, ..., -1.86395006,
        -0.85888106,  0.0473742 ]])

In [48]:
pca.explained_variance_ratio_

array([0.30242178, 0.1569358 , 0.10336001, 0.10162197, 0.0776982 ,
       0.06077671, 0.05123417, 0.03639246, 0.03187815, 0.02570992,
       0.02100951])

In [49]:
X.shape

(29749, 13)